### ISSUE TITLE
Output from the pycppad function is not being accepted by constraint function

### ISSUE THREAD

**Issue by smahajan07** [Photogrammetry-Robotics-Bonn/extrinsic_calibration#1]
Pycppad uses two functions independent and adfun in the [following way](https://github.com/PRBonn/extrinsic_calibration/blob/master/calibration.py#L17-L18)
```
a_var = independent(np.hstack([x0, l0]))
jacobian = adfun(a_var, g(a_var[:dim_x], a_var[dim_x:])).jacobian
```
But when the ```g``` function is called, it calls ```ax2Rot``` and both of these are expecting float values whereas what they get looks like this
```
[<pycppad.cppad_.a_float object at 0x7f358ab170c8>
 <pycppad.cppad_.a_float object at 0x7f358ab17140>
 <pycppad.cppad_.a_float object at 0x7f358ab171b8>]
```

Attaching the screenshot of the error.
![Screenshot from 2019-10-23 09-54-54](https://user-images.githubusercontent.com/28476862/67416800-55752080-f57c-11e9-9c71-d488849047f8.png)

**Comment by dlutguobin** [comment]
same problem

**Comment by Torchmm** [comment]
same problem,have you guys solved this?

**Comment by JanezCim** [comment]
Same problem.

**Comment by yenkn** [comment]
run `pip install -U numpy` works for me.

see commit https://github.com/numpy/numpy/commit/e33b286755401d81a96bb2d847b46c3096ac9903

**Comment by mehditlili** [comment]
Are you guys using pycppad from here https://github.com/b45ch1/pycppad.git ?
Because from what I see it doesn't really compile on Ubuntu 18.04 or newer and I had to adapt it.
This one seems the newer still maintained version https://github.com/bradbell/cppad_py but it seems to have a different API and GPL license.
